from pathlib import Path

Import("env")


def _asm_path_literal(path: Path) -> str:
    return str(path).replace("\\", "\\\\").replace('"', '\\"')


def _write_txt_embed(output: Path, source: Path, symbol: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "\n".join(
            [
                "/* Generated by scripts/generate_embed_sources.py. */",
                ".section .rodata",
                ".balign 4",
                f".global _binary_{symbol}_start",
                f"_binary_{symbol}_start:",
                f'.incbin "{_asm_path_literal(source)}"',
                ".byte 0",
                f".global _binary_{symbol}_end",
                f"_binary_{symbol}_end:",
                f".global _binary_{symbol}_size",
                f"_binary_{symbol}_size:",
                f".long _binary_{symbol}_end - _binary_{symbol}_start",
                "",
            ]
        )
    )


project_dir = Path(env.subst("$PROJECT_DIR"))
build_dir = Path(env.subst("$BUILD_DIR"))
framework_dir = env.PioPlatform().get_package_dir("framework-espidf")
if framework_dir:
    env.Append(
        CPPPATH=[
            str(Path(framework_dir) / "components" / "esp_driver_dma" / "include"),
            str(Path(framework_dir) / "components" / "esp_driver_i2c" / "include"),
        ]
    )

wifi_assets = project_dir / "managed_components" / "78__esp-wifi-connect" / "assets"
nv3023_source = project_dir / "managed_components" / "78__esp_lcd_nv3023" / "esp_lcd_nv3023.c"
uart_uhci_cmake = project_dir / "managed_components" / "78__uart-uhci" / "CMakeLists.txt"
uart_uhci_source = project_dir / "managed_components" / "78__uart-uhci" / "src" / "uart_uhci.cc"

_write_txt_embed(
    build_dir / "wifi_configuration.html.S",
    wifi_assets / "wifi_configuration.html",
    "wifi_configuration_html",
)
_write_txt_embed(
    build_dir / "wifi_configuration_done.html.S",
    wifi_assets / "wifi_configuration_done.html",
    "wifi_configuration_done_html",
)

if nv3023_source.exists():
    nv3023_text = nv3023_source.read_text()
    old = """#else
    switch (panel_dev_config->rgb_endian) {
    case LCD_RGB_ENDIAN_RGB:
        nv3023->madctl_val = 0;
        break;
    case LCD_RGB_ENDIAN_BGR:
        nv3023->madctl_val |= LCD_CMD_BGR_BIT;
        break;
    default:
        ESP_GOTO_ON_FALSE(false, ESP_ERR_NOT_SUPPORTED, err, TAG, "unsupported rgb endian");
        break;
    }
#endif
"""
    new = """#elif ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(6, 0, 0)
    switch (panel_dev_config->rgb_ele_order) {
    case LCD_RGB_ELEMENT_ORDER_RGB:
        nv3023->madctl_val = 0;
        break;
    case LCD_RGB_ELEMENT_ORDER_BGR:
        nv3023->madctl_val |= LCD_CMD_BGR_BIT;
        break;
    default:
        ESP_GOTO_ON_FALSE(false, ESP_ERR_NOT_SUPPORTED, err, TAG, "unsupported rgb element order");
        break;
    }
#else
    switch (panel_dev_config->rgb_endian) {
    case LCD_RGB_ENDIAN_RGB:
        nv3023->madctl_val = 0;
        break;
    case LCD_RGB_ENDIAN_BGR:
        nv3023->madctl_val |= LCD_CMD_BGR_BIT;
        break;
    default:
        ESP_GOTO_ON_FALSE(false, ESP_ERR_NOT_SUPPORTED, err, TAG, "unsupported rgb endian");
        break;
    }
#endif
"""
    if old in nv3023_text:
        nv3023_source.write_text(nv3023_text.replace(old, new))

if uart_uhci_cmake.exists():
    cmake_text = uart_uhci_cmake.read_text()
    if "esp_driver_dma" not in cmake_text:
        uart_uhci_cmake.write_text(
            cmake_text.replace(
                "        esp_mm\n        esp_driver_uart",
                "        esp_mm\n        esp_driver_dma\n        esp_driver_uart",
            )
        )

if uart_uhci_source.exists():
    source_text = uart_uhci_source.read_text()
    old = """    gdma_channel_alloc_config_t rx_alloc = {};
    rx_alloc.direction = GDMA_CHANNEL_DIRECTION_RX;
    ESP_RETURN_ON_ERROR(gdma_new_ahb_channel(&rx_alloc, &rx_dma_chan_), kTag, "RX DMA alloc failed");
"""
    new = """    gdma_channel_alloc_config_t rx_alloc = {};
    ESP_RETURN_ON_ERROR(gdma_new_ahb_channel(&rx_alloc, nullptr, &rx_dma_chan_), kTag, "RX DMA alloc failed");
"""
    if old in source_text:
        uart_uhci_source.write_text(source_text.replace(old, new))
